### ISSUE TITLE
Plugin options not visible

### ISSUE THREAD

**Issue by clintlalonde** [creativecommons/wordpress-plugin#18]
WP 4.7 using default 2017 theme.
New clean install of WP.
Installed awesome branch of plugin & activated plugin. Can't seem to find options in the admin interface to set config options (CC license type, etc). Nor are there options on individual posts to set licenses.
![bugshot2](https://cloud.githubusercontent.com/assets/679506/21058209/cc4a01a0-bdf1-11e6-8752-c91747363242.PNG)
![bugshot1](https://cloud.githubusercontent.com/assets/679506/21058210/ce56300e-bdf1-11e6-9098-490dc7f6498e.PNG)

**Comment by robmyers** [comment]
Please try the latest version? I refactored the main class so that it gets called in the right place now.

**Comment by clintlalonde** [comment]
Fixed, thanks!
