### ISSUE TITLE
Does it support WordPress 4.2?

### ISSUE THREAD

**Issue by mattl** [creativecommons/wordpress-plugin#2]
It would be good to get a release out.

**Comment by tarmot** [comment]
It should support 4.2. I'll verify this soon (latest tomorrow). And yes, getting a release out would be good. :)

**Comment by tarmot** [comment]
Verified. Works as it should.

**Comment by BjornW** [comment]
Hi guys,

I'm (still) finishing renovations and don't have time until after 15 May 
to create a proper release. @Tarmo: are you able to create a new release 
before that?

grtz
BjornW

On 21-04-15 17:58, Tarmo Toikkanen wrote:
>
> Closed #2 <https://github.com/creativecommons/wordpress-plugin/issues/2>.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/creativecommons/wordpress-plugin/issues/2#event-286366720>.
>


-- 

met vriendelijke groet,
Bjorn Wijers

* b u r o b j o r n .nl *
digitaal vakmanschap | digital craftsmanship

Postbus 14145
3508 SE Utrecht
The Netherlands

tel: +31 6 49 74 78 70
http://www.burobjorn.nl

**Comment by tarmot** [comment]
The code is basically working as it should. Not sure what all needs to be done, really. Some polishing up of documentation, and certainly the UI texts can be looked over and improved.
